In [25]:
from datasets import load_dataset
from huggingface_hub import login
import pandas as pd
import os
from pathlib import Path
from dotenv import load_dotenv

# .env aus dem Projektstamm laden (zwei Ebenen über diesem Notebook)
load_dotenv(Path(__file__).parents[2] / ".env" if "__file__" in dir() else Path("../.env"))

hf_token = os.getenv("HF_TOKEN")
if not hf_token:
    raise EnvironmentError("HF_TOKEN nicht gefunden – bitte in der .env-Datei setzen.")
login(token=hf_token)

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

In [26]:

# 1. Download/Load the dataset
print("Fetching Amaan/DataDays...")
dataset = load_dataset("Amaan/DataDays")

# 2. Look at what's inside
print("\n--- Dataset Info ---")
print(dataset)


# 3. Access a specific row (e.g., first row of the 'train' split)
# Note: Check the output of step 2 to see if your data uses 'train'
if 'train' in dataset:
    print("\n--- First Entry Sample ---")
    print(dataset['train'][0])

Fetching Amaan/DataDays...

--- Dataset Info ---
DatasetDict({
    train: Dataset({
        features: ['FID', 'feed_id', 'station_id', 'name', 'capacity', 'is_virtual_station', 'num_cars_available', 'num_bicycles_available', 'num_scooters_available', 'num_cargo_bicycles_available', 'num_mopeds_available', 'rental_uris_android', 'rental_uris_ios', 'rental_uris_web', 'last_reported', 'realtime_data_outdated', 'geometry', 'datastore_updated_at'],
        num_rows: 2721492
    })
})

--- First Entry Sample ---
{'FID': 'sharing_stations.NBV:Station:10046976', 'feed_id': 'nextbike_vn', 'station_id': 'NBV:Station:10046976', 'name': 'Ortsmitte / Unterdorfstraße', 'capacity': 4.0, 'is_virtual_station': 'f', 'num_cars_available': None, 'num_bicycles_available': 4, 'num_scooters_available': None, 'num_cargo_bicycles_available': None, 'num_mopeds_available': None, 'rental_uris_android': 'https://app.nextbike.net/station?id=10046976', 'rental_uris_ios': 'https://app.nextbike.net/station?id=10046976', 'rental_uris_web': 'https://nxtb.it/p/10046976', 'last_reported': '2026-02-01 01:31:42+01', 'realtime_data_outdated': 'f', 'geometry': 'POINT (8.601469 49.504677)', 'datastore_updated_at': '2026-02-01 01:32:32+01'}

In [27]:
df = dataset["train"].to_pandas()
df.head()

,FID,feed_id,station_id,name,capacity,is_virtual_station,num_cars_available,num_bicycles_available,num_scooters_available,num_cargo_bicycles_available,num_mopeds_available,rental_uris_android,rental_uris_ios,rental_uris_web,last_reported,realtime_data_outdated,geometry,datastore_updated_at
0,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,NaN,4,NaN,NaN,NaN,https://app.nextbike.net/station?id=10046976,https://app.nextbike.net/station?id=10046976,https://nxtb.it/p/10046976,2026-02-01 01:31:42+01,f,POINT (8.601469 49.504677),2026-02-01 01:32:32+01
1,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,NaN,4,NaN,NaN,NaN,https://app.nextbike.net/station?id=10046976,https://app.nextbike.net/station?id=10046976,https://nxtb.it/p/10046976,2026-02-01 01:52:42+01,f,POINT (8.601469 49.504677),2026-02-01 01:53:41+01
2,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,NaN,4,NaN,NaN,NaN,https://app.nextbike.net/station?id=10046976,https://app.nextbike.net/station?id=10046976,https://nxtb.it/p/10046976,2026-02-01 02:08:19+01,f,POINT (8.601469 49.504677),2026-02-01 02:09:33+01
3,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,NaN,4,NaN,NaN,NaN,https://app.nextbike.net/station?id=10046976,https://app.nextbike.net/station?id=10046976,https://nxtb.it/p/10046976,2026-02-01 01:05:32+01,f,POINT (8.601469 49.504677),2026-02-01 01:06:09+01
4,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,NaN,4,NaN,NaN,NaN,https://app.nextbike.net/station?id=10046976,https://app.nextbike.net/station?id=10046976,https://nxtb.it/p/10046976,2026-02-01 01:14:49+01,f,POINT (8.601469 49.504677),2026-02-01 01:16:42+01

In [4]:
### Handle missing values
# missing capacity values with 0
df['capacity'] = df['capacity'].fillna(0)

# drop columns with cars, scooters, cargo bikes, and mopeds
columns_to_drop = ['num_cars_available', 'num_scooters_available', 'num_cargo_bicycles_available', 'num_mopeds_available', 'rental_uris_android', 'rental_uris_ios', 'rental_uris_web']
df = df.drop(columns=columns_to_drop)

In [5]:
df.head(10)

,FID,feed_id,station_id,name,capacity,is_virtual_station,num_bicycles_available,last_reported,realtime_data_outdated,geometry,datastore_updated_at
0,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 01:31:42+01,f,POINT (8.601469 49.504677),2026-02-01 01:32:32+01
1,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 01:52:42+01,f,POINT (8.601469 49.504677),2026-02-01 01:53:41+01
2,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 02:08:19+01,f,POINT (8.601469 49.504677),2026-02-01 02:09:33+01
3,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 01:05:32+01,f,POINT (8.601469 49.504677),2026-02-01 01:06:09+01
4,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 01:14:49+01,f,POINT (8.601469 49.504677),2026-02-01 01:16:42+01
5,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 00:22:57+01,f,POINT (8.601469 49.504677),2026-02-01 00:23:50+01
6,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 23:58:00+01,f,POINT (8.601469 49.504677),2026-02-01 23:59:52+01
7,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 00:38:12+01,f,POINT (8.601469 49.504677),2026-02-01 00:39:46+01
8,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 02:03:04+01,f,POINT (8.601469 49.504677),2026-02-01 02:04:16+01
9,sharing_stations.NBV:Station:10046976,nextbike_vn,NBV:Station:10046976,Ortsmitte / Unterdorfstraße,4.0,f,4,2026-02-01 00:54:50+01,f,POINT (8.601469 49.504677),2026-02-01 00:55:36+01

In [6]:
# check for columns with missing values
df.columns[df.isna().any()].tolist()

[]

In [7]:
# Erlaubt sind: a-z, A-Z, 0-9, Leerzeichen (\s), Punkt, Komma, Bindestrich und äöüÄÖÜß
# Alles andere wird herausgefiltert und angezeigt!
fremde_zeichen = df[df['name'].str.contains(r'[^a-zA-Z0-9\s.,\-/äöüÄÖÜß]', regex=True, na=False)]

# Schau dir an, was hängengeblieben ist
print(fremde_zeichen['name'])

7570                          INF – Universitätsklinikum/Zoo
7571                          INF – Universitätsklinikum/Zoo
7572                          INF – Universitätsklinikum/Zoo
7573                          INF – Universitätsklinikum/Zoo
7574                          INF – Universitätsklinikum/Zoo
                                 ...
2718162    rnv Betriebshof Ludwigshafen (keine öffentlich...
2718163    rnv Betriebshof Ludwigshafen (keine öffentlich...
2718164    rnv Betriebshof Ludwigshafen (keine öffentlich...
2718165    rnv Betriebshof Ludwigshafen (keine öffentlich...
2718166    rnv Betriebshof Ludwigshafen (keine öffentlich...
Name: name, Length: 152348, dtype: str

In [11]:
import geopandas as gpd
from shapely.wkt import loads

# 1. WKT-Strings in echte Geometrie-Objekte umwandeln (behebt deinen TypeError)
df['geometry'] = df['geometry'].apply(lambda x: loads(x) if isinstance(x, str) else x)

# 2. In ein GeoDataFrame umwandeln
gdf = gpd.GeoDataFrame(df, geometry='geometry', crs="EPSG:4326")

# 3. Mannheim-Grenze laden
mannheim_boundary = gpd.read_file("OSMB-07946053ba77766c423655ac17c41565bf60514d.geojson")

# 4. Koordinatensysteme abgleichen
mannheim_boundary = mannheim_boundary.to_crs(gdf.crs)

# 5. Räumlicher Filter: Nur Stationen innerhalb der Grenze behalten
df_mannheim = gpd.sjoin(gdf, mannheim_boundary, predicate='within')

# 6. Aufräumen: Spalten vom Join entfernen, die wir nicht brauchen
df_mannheim = df_mannheim.drop(columns=['index_right'], errors='ignore')

# Jetzt kannst du mit deinem restlichen 'df_ml = df_mannheim.copy()' Code weitermachen

In [14]:
df_mannheim.shape

(683420, 22)

In [20]:
### prepare set for training
df_ml = df_mannheim.copy()
# handle geometry objects
if 'geometry' in df_ml.columns:
    df_ml['Laengengrad'] = df_ml.geometry.x
    df_ml['Breitengrad'] = df_ml.geometry.y
    df_ml = df_ml.drop(columns=['geometry'])

# handle time objects
df_ml['last_reported'] = pd.to_datetime(df_ml['last_reported'], errors='coerce')

df_ml['Stunde'] = df_ml['last_reported'].dt.hour
df_ml['Wochentag'] = df_ml['last_reported'].dt.dayofweek
df_ml['Monat'] = df_ml['last_reported'].dt.month

df_ml = df_ml.drop(columns=['last_reported'])

# handle boolean values:
mapping = {
    'True': 1, 'False': 0,
    'true': 1, 'false': 0,
    'T': 1, 'F': 0,
    't': 1, 'f': 0,
    '1': 1, '0': 0,
    True: 1, False: 0,
    1: 1, 0: 0
}

# Wir nutzen .map() statt .replace(), das verhindert die FutureWarnings
df_ml['is_virtual_station'] = df_ml['is_virtual_station'].map(mapping).astype(float)
df_ml['realtime_data_outdated'] = df_ml['realtime_data_outdated'].map(mapping).astype(float)

# remove unnecessary data
df_ml = df_ml.rename(columns={'name_left': 'name'})
df_ml = df_ml.drop(columns=['FID', 'feed_id', 'datastore_updated_at'])
osm_muell = [
    'osm_id', 'name_right', 'name_en', 'boundary', 'admin_level',
    'admin_centre_node_id', 'admin_centre_node_lat', 'admin_centre_node_lng',
    'label_node_id', 'label_node_lat', 'label_node_lng'
]

# ... und weg damit!
df_ml = df_ml.drop(columns=osm_muell, errors='ignore')

df_ml.head(10)

,station_id,name,capacity,is_virtual_station,num_bicycles_available,realtime_data_outdated,Laengengrad,Breitengrad,Stunde,Wochentag,Monat
8654,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,4,0.0,8.463662,49.477082,10,6,2
8655,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,5,0.0,8.463662,49.477082,12,6,2
8656,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,4,0.0,8.463662,49.477082,11,6,2
8657,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,4,0.0,8.463662,49.477082,10,6,2
8658,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,4,0.0,8.463662,49.477082,11,6,2
8659,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,5,0.0,8.463662,49.477082,11,6,2
8660,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,4,0.0,8.463662,49.477082,11,6,2
8661,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,5,0.0,8.463662,49.477082,11,6,2
8662,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,5,0.0,8.463662,49.477082,12,6,2
8663,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,0.0,4,0.0,8.463662,49.477082,10,6,2

In [21]:
# define target and input features
y = df_ml['num_bicycles_available']

X = df_ml.drop(columns=['num_bicycles_available', 'station_id', 'name'])

print(X.dtypes)

capacity                  float64
is_virtual_station        float64
realtime_data_outdated    float64
Laengengrad               float64
Breitengrad               float64
Stunde                      int32
Wochentag                   int32
Monat                       int32
dtype: object

In [24]:
df_mannheim.head()

,FID,feed_id,station_id,name_left,capacity,is_virtual_station,num_bicycles_available,last_reported,realtime_data_outdated,geometry,...,name_right,name_en,boundary,admin_level,admin_centre_node_id,admin_centre_node_lat,admin_centre_node_lng,label_node_id,label_node_lat,label_node_lng
8654,sharing_stations.NBV:Station:121376,nextbike_vn,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,f,4,2026-02-01 10:27:31+01,f,POINT (8.46366 49.47708),...,Mannheim,Mannheim,administrative,6,240060919,49.489291,8.46731,None,None,None
8655,sharing_stations.NBV:Station:121376,nextbike_vn,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,f,5,2026-02-01 12:24:58+01,f,POINT (8.46366 49.47708),...,Mannheim,Mannheim,administrative,6,240060919,49.489291,8.46731,None,None,None
8656,sharing_stations.NBV:Station:121376,nextbike_vn,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,f,4,2026-02-01 11:42:14+01,f,POINT (8.46366 49.47708),...,Mannheim,Mannheim,administrative,6,240060919,49.489291,8.46731,None,None,None
8657,sharing_stations.NBV:Station:121376,nextbike_vn,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,f,4,2026-02-01 10:59:55+01,f,POINT (8.46366 49.47708),...,Mannheim,Mannheim,administrative,6,240060919,49.489291,8.46731,None,None,None
8658,sharing_stations.NBV:Station:121376,nextbike_vn,NBV:Station:121376,Lindenhof - Jugendherberge,6.0,f,4,2026-02-01 11:37:20+01,f,POINT (8.46366 49.47708),...,Mannheim,Mannheim,administrative,6,240060919,49.489291,8.46731,None,None,None